basePath: /
definitions:
  requests.Signin:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  requests.Signup:
    properties:
      password:
        type: string
      password_confirmation:
        type: string
      username:
        type: string
    required:
    - password
    - password_confirmation
    - username
    type: object
  responses.Token:
    properties:
      token:
        type: string
    type: object
  responses.User:
    properties:
      id:
        type: integer
      username:
        type: string
    type: object
  responses.httpError:
    properties:
      error:
        type: object
    type: object
info:
  contact: {}
  title: Users
  version: "1.0"
paths:
  /signin:
    post:
      consumes:
      - application/json
      parameters:
      - description: Зарегистрировать пользователя
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/requests.Signin'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.Token'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.httpError'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/responses.httpError'
      summary: Вход в систему
      tags:
      - users
  /signup:
    post:
      consumes:
      - application/json
      parameters:
      - description: Зарегистрировать пользователя
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/requests.Signup'
      responses:
        "201": {}
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.httpError'
      summary: Регистрация пользователя в системе
      tags:
      - users
  /users/:id:
    get:
      consumes:
      - application/json
      parameters:
      - description: ID пользователя
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.httpError'
        "403":
          description: Forbidden
          schema:
            $ref: '#/definitions/responses.httpError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.httpError'
      summary: Запрос пользователя в системе по ID
      tags:
      - users
swagger: "2.0"
