basePath: /
definitions:
  requests.RegisterUser:
    properties:
      password:
        type: string
      password_confirmation:
        type: string
      username:
        type: string
    required:
    - password
    - password_confirmation
    - username
    type: object
  responses.httpError:
    properties:
      error:
        type: object
    type: object
info:
  contact: {}
  title: Users
  version: "1.0"
paths:
  /users:
    post:
      consumes:
      - application/json
      parameters:
      - description: Зарегистрировать пользователя
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/requests.RegisterUser'
      responses:
        "201": {}
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.httpError'
      summary: Регистрация пользователя в системе
      tags:
      - users
swagger: "2.0"
